### ISSUE TITLE
Warning when compiled by GCC 5.1 upwards with -Wabi-tag

### ISSUE THREAD

**Issue by smradCZ** [banditcpp/snowhouse#36]
```
#include <snowhouse/snowhouse.h>
int main()
{
  return 0;
}
```

When code above is compiled by GCC 5.1 upwards with -Wabi-tag, compilation throws many errors like this:
```
In file included from ../snowhouse/fluent/operators/constraintoperator.h:10:0,
                 from ../snowhouse/fluent/fluent.h:12,
                 from ../snowhouse/snowhouse.h:26,
                 from a.cc:1:
../snowhouse/fluent/operators/invalidexpressionexception.h:12:10: warning: ‘snowhouse::InvalidExpressionException’ does not have the "cxx11" ABI tag that ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’ (used in the type of ‘snowhouse::InvalidExpressionException::m_message’) has [-Wabi-tag]
   struct InvalidExpressionException
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
../snowhouse/fluent/operators/invalidexpressionexception.h:23:17: note: ‘snowhouse::InvalidExpressionException::m_message’ declared here
     std::string m_message;
```

It was caused by Dual ABI (introduced in GCC 5.1) which changes std::string implementation among other changes. Some other pinpoints follows:
- see last paragraph in Troubleshooting on https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html - it describes issues on snowhouse - methods returing std::string or class having member variable of type std::string.
- case (c) on https://greek0.net/blog/2016/10/29/gcc_compatibility/ - this article describes how it works
- on some mailing thread I found answer which proves my opinion about -Wabi-tag option, it look likewise:
    Q: "Why -Wall or -Wextra doesn't include -Wabi-tag by default?" >> A: "Because it is useful mainly for library vendors"

The abi-tag option checks only member variables and returned types of functions/methods which are not tagged, other usage of std::string is OK
For example the std::string in param corresponds to std::__cxx11::string (from inline namespace defined in libstdc++) and this type has different mangle name than std::string. But the warning informs that cxx11 is inherited for returned type as well.

Affected classes with member variables of type std::string and returning std::string from methods could be "annotated" by _GLIBCXX_DEFAULT_ABI_TAG to get rid of these warnings. See /usr/lib/...../bits/c++config.h where _GLIBCXX_DEFAULT_ABI_TAG macro is defined as alias to _GLIBCXX_ABI_TAG_CXX11 which refers to '__attribute ((_abi_tag__ ("cxx11")))'.

Warnings shouldn't be thrown here IMHO, but the question is how to fix it?

**Comment by sbeyer** [comment]
Thank you very much. I'm hearing about this the first time and I wonder if this is actually a problem since snowhouse/bandit are header-only libraries and hence always compiled with the same ABI as the user code. In other words: the warning does IMHO not make sense for the code at all, so I am also unwilling to tag the code.

However, I see that if you are using snowhouse/bandit for your library tests and you use `-Wabi-tag` for your whole code base (including tests), this is a problem. One solution would be to declare bandit/snowhouse as system headers with the `-isystem` option. Maybe I get better ideas.

Also note that bandit (but not snowhouse) is C++11-only, so setting `-D_GLIBCXX_USE_CXX11_ABI=1` in the `CXXFLAGS` is safe. If I understood the scenario correctly, this should silence the warnings. (However, on my g++7, setting it to `0` silences the warnings, setting it to `1` does not... So: for a C++11-only setting, do not use `-Wabi-tag`?)

**Comment by smradCZ** [comment]
Thank you for reply.

Generally you are right, `-Wabi-tag` is useless for header-only libs, for building final app binary as well.
There is probably only one case where `-Wabi-tag` give benefits to us - building a library.

In our case we want `-Wabi-tag` option enabled because we use this code on wrapping library which is not header-only and it can cause potential issues on linking.

Thanks for `-isystem` option, I didn't know that. It can help me to figure out how to avoid useless warnings from snowhouse.

I think you can close this issue as `Won't fix`.
